capacity:
  service:
    user: CAPACITY_SERVICE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/capacity_service
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver